// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240716234852_AddStatusColumnCorrectly")]
    partial class AddStatusColumnCorrectly
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api.Model.ReservationDB", b =>
                {
                    b.Property<int?>("book_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("book_id"), 1L, 1);

                    b.Property<int?>("CityID")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<int?>("DL_country")
                        .HasColumnType("int")
                        .HasColumnName("DL_country");

                    b.Property<DateTime?>("DL_dt_expiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("DL_dt_expiry");

                    b.Property<string>("DL_number")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DL_number");

                    b.Property<int?>("DL_province")
                        .HasColumnType("int")
                        .HasColumnName("DL_province");

                    b.Property<int?>("Renter2_DL_country")
                        .HasColumnType("int")
                        .HasColumnName("Renter2_DL_country");

                    b.Property<DateTime?>("Renter2_DL_dt_expiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("Renter2_DL_dt_expiry");

                    b.Property<string>("Renter2_DL_number")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Renter2_DL_number");

                    b.Property<int?>("Renter2_DL_province")
                        .HasColumnType("int")
                        .HasColumnName("Renter2_DL_province");

                    b.Property<string>("Renter2_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Renter2_Name");

                    b.Property<string>("Renter2_Relation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Renter2_Relation");

                    b.Property<int?>("Renter2_birth_year")
                        .HasColumnType("int")
                        .HasColumnName("Renter2_birth_year");

                    b.Property<int?>("StateProvinceID")
                        .HasColumnType("int")
                        .HasColumnName("StateProvinceID");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("address_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_1");

                    b.Property<string>("address_2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_2");

                    b.Property<int?>("birth_year")
                        .HasColumnType("int")
                        .HasColumnName("birth_year");

                    b.Property<string>("bk_comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bk_comments");

                    b.Property<string>("bookref")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bookref");

                    b.Property<int?>("booksource_id")
                        .HasColumnType("int")
                        .HasColumnName("booksource_id");

                    b.Property<int?>("car_class")
                        .HasColumnType("int")
                        .HasColumnName("car_class");

                    b.Property<string>("cdw_addinfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cdw_addinfo");

                    b.Property<string>("cdw_desc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cdw_desc");

                    b.Property<DateTime?>("cdw_expiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("cdw_expiry");

                    b.Property<string>("cdw_policy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cdw_policy");

                    b.Property<int?>("cdw_province")
                        .HasColumnType("int")
                        .HasColumnName("cdw_province");

                    b.Property<string>("cdw_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cdw_type");

                    b.Property<string>("cell_phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cell_phone");

                    b.Property<string>("cp_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cp_code");

                    b.Property<DateTime?>("dob_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("dob_date");

                    b.Property<DateTime?>("dob_date_2")
                        .HasColumnType("datetime2")
                        .HasColumnName("dob_date_2");

                    b.Property<bool?>("dropoff_offsite")
                        .HasColumnType("bit")
                        .HasColumnName("dropoff_offsite");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("fam_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fam_name");

                    b.Property<string>("flight_no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("flight_no");

                    b.Property<bool?>("imgs_verified")
                        .HasColumnType("bit")
                        .HasColumnName("imgs_verified");

                    b.Property<string>("location2_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location2_code");

                    b.Property<string>("location2_comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location2_comment");

                    b.Property<int?>("location2_id")
                        .HasColumnType("int")
                        .HasColumnName("location2_id");

                    b.Property<string>("location_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_code");

                    b.Property<string>("location_comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_comment");

                    b.Property<int?>("location_id")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal?>("paid_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("pcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pcode");

                    b.Property<bool?>("pickup_offsite")
                        .HasColumnType("bit")
                        .HasColumnName("pickup_offsite");

                    b.Property<int?>("rental_days")
                        .HasColumnType("int")
                        .HasColumnName("rental_days");

                    b.Property<DateTime?>("tdt_car_in")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdt_car_in");

                    b.Property<DateTime?>("tdt_car_out")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdt_car_out");

                    b.Property<decimal?>("total_charge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_charge");

                    b.Property<decimal?>("total_hst")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_hst");

                    b.HasKey("book_id");

                    b.ToTable("to_Bookings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
